---
title: bikepacking jojos
timezone: Europe/Berlin
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Follow Johanna & Johannes bikepacking sabbatical. 8 countries • 5.500km
  • 2 gravel bikes • 1 Tent • Berlin - Malaga
baseurl: "/bikepacking-jojos.de"
url: 
github_repo: nevvkid/bikepacking-jojos.de
github_username: nevvkid
github:
- metadata
social_link: instagram
social_username: bikepacking_jojos
remote_theme: broccolini/swiss
theme_color: white
markdown: kramdown
plugins:
- jekyll-feed
