# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: bikepacking jojos
description: Follow Johanna & Johannes bikepacking sabbatical. 8 countries • 5.500km • 2 gravel bikes • 1 Tent • Berlin - Malaga

baseurl: "/bikepacking-jojos.de" # the subpath of your site, e.g. /blog
url: "https://nevvkid.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_repo: nevvkid/bikepacking-jojos.de # the GitHub repo name for your project
github_username: nevvkid
github: [metadata]

# Optional social link, you can choose from the following options:
# twitter (default), instagram, medium, or dribbble
social_link: instagram
social_username: bikepacking_jojos

# Remote Theme
remote_theme: broccolini/swiss

# Set theme color here
# Choose from: black (default), blue, gray, magenta, orange, red, white, and yellow.
theme_color: white

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

